import json, copy, os, sys

with open('/Users/aanchalbhatia/Desktop/Aanchal/tlt/json-res/tara_by_mahesh_dattani_summary_in_hindi_-dz1jvj5qIE.json') as f:
    d = json.load(f)

print('video_id:', d.get('video_id'))
print('title:', d.get('title'))
print('channel:', d.get('channel'))
print('published_at:', d.get('published_at'))
print('duration_seconds:', d.get('duration_seconds'))
print('language:', d.get('language'))
print('tags:', d.get('tags'))
print('---DESCRIPTION---')
print(d.get('description', '')[:800])
t = d.get('transcript', {})
print('---TRANSCRIPT_AVAILABLE---', t.get('available'))
print('---FULL_TEXT_LEN---', len(t.get('full_text','')))
print('---FULL_TEXT_PART1---')
print(t.get('full_text','')[:4000])
print('---FULL_TEXT_PART2---')
print(t.get('full_text','')[4000:8000])
print('---FULL_TEXT_PART3---')
print(t.get('full_text','')[8000:12000])
print('---FULL_TEXT_PART4---')
print(t.get('full_text','')[12000:16000])
print('---FULL_TEXT_PART5---')
print(t.get('full_text','')[16000:20000])
